name: 'crypto_warehouse'
version: '1.0.0'
config-version: 2

profile: 'crypto_warehouse'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_warehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  crypto_warehouse:
    +column_types:
      SNo: integer
      High: double
      Low: double
      Open: double
      Close: double
      Volume: double
      Marketcap: double
